### ISSUE TITLE
shardingStrategy of session created with createReadSession is always SHARDING_STRATEGY_UNSPECIFIED

### ISSUE THREAD

**Issue by tetsu5555** [googleapis/nodejs-bigquery-storage#114]
#### Environment details

  - OS: MacOS
  - Node.js version: v10.16.3
  - npm version: 6.9.0
  - `@google-cloud/bigquery-storage` version:

#### Steps to reproduce

  1. clone this repository
  2. setup Service account
  3. [change argument for createSession](https://github.com/googleapis/nodejs-bigquery-storage/blob/64aa20e0164b93442bd46c67a48f09de53994826/samples/quickstart.js#L71) to ↓

```
    // API request.
    const request = {
      tableReference,
      parent,
      readOptions,
      tableModifiers,
      format: 'AVRO',

      // changed here↓
      shardingStrategy: 'BALANCED',
      requestedStreams: 10
    };

    const [session] = await client.createReadSession(request);
    console.log(session.shardingStrategy) // SHARDING_STRATEGY_UNSPECIFIED

```

  4. run `samples/quickstart.js`

**Comment by steffnay** [comment]
The ability to set shardingStrategy in createReadSession() requests was removed in v1, so this quickstart is out of date. I will update to reflect the current request structure. Documentation on this can be found here: https://cloud.devsite.corp.google.com/bigquery/docs/reference/storage/rpc/google.cloud.bigquery.storage.v1#google.cloud.bigquery.storage.v1.CreateReadSessionRequest

**Comment by tetsu5555** [comment]
@steffnay 
Thanks for you reply and updating sample for v1 client.😄

> Documentation on this can be found here:

I checked, but document seems to be only internal(?), please check🙏


<img width="1767" alt="スクリーンショット 2020-10-15 18 04 18" src="https://user-images.githubusercontent.com/34498252/96101922-ec1aba00-0f10-11eb-96b7-6423041fd0d6.png">

**Comment by steffnay** [comment]
@tetsu5555 woops! here is the correct link: https://cloud.google.com/bigquery/docs/reference/storage/rpc/google.cloud.bigquery.storage.v1#google.cloud.bigquery.storage.v1.CreateReadSessionRequest
