### ISSUE TITLE
Inconsistent Write API results

### ISSUE THREAD

**Issue by s1moe2** [googleapis/nodejs-bigquery-storage#227]
#### Environment details

  - OS: MacOS 11.6 & Ubuntu 20.04
  - Node.js version: v14 & v16
  - npm version: 8.1.0
  - `@google-cloud/bigquery-storage` version: 2.7.0

Note: This bug report follows the discussion started in [this issue](https://github.com/googleapis/nodejs-bigquery-storage/issues/222), around some apparently random permission errors when using the write storage API.

#### Steps to reproduce

The code that was used to reproduce this issue can be found in this also related [stackoverflow answer](https://stackoverflow.com/a/70024956/6593337).

- created a new BigQuery dataset
- created a new table with the following structure: 
![image](https://user-images.githubusercontent.com/36140182/143789326-a9523275-a128-49f4-98ae-b4c7a6cc0b2a.png)
- created a service account with the BigQuery Admin role and created a JSON key
- executed the code with success 2 times (one with node directly and another in a docker image)

More details below:

I had this same problem with the same code on Ubuntu 20.04 (nodejs v14). Decided to try this on a macbook (nodejs v16) to rule out an os/env issue. Created a clean project, used an exact copy of the code from @rayeeskm and it worked:
<img width="318" alt="Screenshot 2021-11-28 at 21 47 45" src="https://user-images.githubusercontent.com/36140182/143787325-3846d889-4a63-4254-a8ff-15475963a615.png">

Then I decided to run with Docker, in an node16-alpine image. Worked:
<img width="920" alt="Screenshot 2021-11-28 at 21 40 42" src="https://user-images.githubusercontent.com/36140182/143787381-98c491ad-afad-46fb-b176-0f3aad7eb407.png">

After this, because what I really needed for my use case would be to use the committed mode, I changed it and ran a test to see what would happen. This time I got the `Permission TABLES_UPDATE_DATA denied on resource`!

So, I reverted all changes to the original code but the error remains.
I also tested the docker version again (I had not made any more builds: the image was still the only one I had built) and it also has the error:
<img width="1128" alt="Screenshot 2021-11-28 at 21 40 57" src="https://user-images.githubusercontent.com/36140182/143787538-3f3e0bc1-02dd-42b7-ae41-9399c6229e17.png">

And here's proof that those two tests (with local node and docker) worked:
<img width="358" alt="Screenshot 2021-11-28 at 21 58 53" src="https://user-images.githubusercontent.com/36140182/143787689-00ddefdd-734e-4d53-8e00-7c182ab4b633.png">

BigQuery Storage API metrics show errors on AppendRows:
![image](https://user-images.githubusercontent.com/36140182/143788635-711054d9-1794-476d-9ac5-4bd9172bd1a6.png)

And they seem to be 403 errors indeed:
![image](https://user-images.githubusercontent.com/36140182/143788937-f703a750-65a3-4d3a-a503-364c6987d798.png)

At this point I'm out of ideas. With this sort of tests/results, could this be related to API usage?
Is there any other piece of data I could look at that would help understand the problem?
At the moment I'm trying to get more info from the Logs Explorer but the most recent attempts (that resulted in an error) are not showing there. I'll update this issue if I get more log details.

**Comment by steffnay** [comment]
@s1moe2 looking into this. Are you using the free tier when you get this error?

**Comment by s1moe2** [comment]
@steffnay no, it's a project with an active billing account.
Thank you

**Comment by s1moe2** [comment]
Also, let me add that I was not able to run the sample code with success again after getting the error 2 days ago. I've tried a few times (with a lot of hours in between) and always get the same error.

**Comment by steffnay** [comment]
@s1moe2 okay, got it. So just so I can make sure I'm doing the right thing in my attempt to reproduce this, it's basically as if you get locked out of your project after you attempt to go from creating the stream with `mode.PENDING` to` mode.COMMITTED`?

**Comment by s1moe2** [comment]
@steffnay Something like that. I can't say 100% for sure that the error started because of that but that it's a start!

**Comment by gal1419** [comment]
@steffnay thanks for looking into this. I'm having the same problem, however, I never was able to run the script from StackOverflow. I keep getting the same permissions error from the first run. as @s1moe2 - my project is configured properly with billing.

**Comment by s1moe2** [comment]
Tried on a new dataset. Something must have changes in the API because now the error message seems to have a bit more info. Not sure if it's helpful to anyone.
```
Error: 7 PERMISSION_DENIED: Permission 'TABLES_UPDATE_DATA' denied on resource 'projects/XXX/datasets/new_ds_eu/tables/student' (or it may not exist).
    at Object.callErrorFromStatus (XXXX/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (XXXX/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
    at Object.onReceiveStatus (XXXX/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (XXXX/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at XXXX/node_modules/@grpc/grpc-js/build/src/call-stream.js:160:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 7,
  details: "Permission 'TABLES_UPDATE_DATA' denied on resource 'projects/XXX/datasets/new_ds_eu/tables/student' (or it may not exist).",
  metadata: Metadata {
    internalRepr: Map(1) { 'grpc-server-stats-bin' => [Array] },
    options: {}
  },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```

**Comment by steffnay** [comment]
@s1moe2 we'll be able to release a fix for this that allows the correct headers to be set for these requests in January.

**Comment by s1moe2** [comment]
Thanks @steffnay !
