### ISSUE TITLE
Use in javascript

### ISSUE THREAD

**Issue by luckyfanghe** [googleapis/nodejs-bigquery-storage#231]
I am going to use this library in javascript.
Server will create only session and send it to client.
And in the client will get rows with the session. It is possible?

**Comment by alvarowolfx** [comment]
Can you expand on your question @luckyfanghe ? We have samples in Javascript for [reading rows using the Storage Read API](https://github.com/googleapis/nodejs-bigquery-storage/blob/main/samples/quickstart.js) and [write rows using the Storage Write API](https://github.com/googleapis/nodejs-bigquery-storage/blob/main/samples/append_rows_pending.js). Does those samples help ?
