### ISSUE TITLE
Usage example without Protobuf (write plain JSON objects)

### ISSUE THREAD

**Issue by galah92** [googleapis/nodejs-bigquery-storage#263]
Hi, current write example heavily rely on schema described using protobuf.
Can I use this library somehow with specifying data as plain JSON objects instead? I don't want to deal with any Protobuf boilerplate.

Thanks

**Comment by shollyman** [comment]
Since this issue was created, a new managedwriter library was created that simplifies json-based writing.  See https://github.com/googleapis/nodejs-bigquery-storage/blob/main/samples/append_rows_json_writer_default.js for an example of using it.
