### ISSUE TITLE
TypeError: Type.fromDescriptor

### ISSUE THREAD

**Issue by chienazazaz** [googleapis/nodejs-bigquery-storage#370]
I'm trying to implement Storage Write API for my pipeline.
The error occurred when I ran
`const writer = new JSONWriter({
      connection,
      protoDescriptor
    })`

The error message:

`TypeError: Type.fromDescriptor is not a function`
`at JSONWriter.setProtoDescriptor (node_modules/.pnpm/@google-cloud+bigquery-storage@4.1.0/node_modules/@google-cloud/bigquery-storage/src/managedwriter/json_writer.ts:94:32)`
`at new JSONWriter (node_modules/.pnpm/@google-cloud+bigquery-storage@4.1.0/node_modules/@google-cloud/bigquery-storage/src/managedwriter/json_writer.ts:71:10)`

On the sample code, I saw you add streamId into JSONWriter constructor as well but I checked the module and it was not required so I got rid of it.

**Comment by fr33z3** [comment]
So what was the reason for an exception? I'm currently receiving the same one.

**Comment by chienazazaz** [comment]
> So what was the reason for an exception? I'm currently receiving the same one.

It was missing dependencies. I add `google-gax@4.0.3` and it works just fine

**Comment by tarunrawat87** [comment]
Facing the same issue, I have google-gax@4.0.3 installed already

**Comment by az-nextsec** [comment]
Same here, I have confirmed I have all dependencies installed but am still getting `Type.fromDescriptor is not a function` in the `JSONWriter`
