### ISSUE TITLE
type JSONList in json_writer is not exported

### ISSUE THREAD

**Issue by huilingwei** [googleapis/nodejs-bigquery-storage#421]
Hi, 

I am using the JSONWriter  appendRows to insert data to Big Query, it accept JSONList as input, but this type is not exported. It is convenient to convert the input to the correct data type. Is it possible to export this type in future release?

Thanks,
Huiling

**Comment by alvarowolfx** [comment]
hey @huilingwei thanks for the report. The `JSONList` is suppose to represent just a list of plain JSON objects. Are you having issues passing such objects to the method ? I was holding back exporting those because they are suppose to be a broader type and not reused in other places, unless is causing problems for users to use it.

**Comment by galah92** [comment]
@alvarowolfx any reason not to use TypeScript's `object[]`? I understand it should be equal to `JSONList`.

**Comment by huilingwei** [comment]
> hey @huilingwei thanks for the report. The `JSONList` is suppose to represent just a list of plain JSON objects. Are you having issues passing such objects to the method ? I was holding back exporting those because they are suppose to be a broader type and not reused in other places, unless is causing problems for users to use it.

We define a common method to insert records, it will accept object[], when  writer.appendRows with rows, build will fail for error: Argument of type T[] is not assignable to parameter of type JSONList
We resolve it by converting rows to never[]: writer.appendRows(rows as never[]) . If JSONList is exported, convert the type to JSONList will be better.
```
const insertCommon = async <T extends object>(
    tableId: string,
    rows: T[],
): Promise<boolean> =>{
  ...
  const pw = writer.appendRows(rows);
  ...
}
```

**Comment by alvarowolfx** [comment]
#420 exports JSONList
