### ISSUE TITLE
How should errors be handled?

### ISSUE THREAD

**Issue by brantian** [googleapis/nodejs-bigquery-storage#454]
Hello! I'm trying to understand the best way to handle errors when using this library. 

I understand there is a Retry logic implemented, so my question is if, in this case, I'm safe to ignore errors emitted by the `StreamConnection`. When a retry attempt is made, is the error emitted by the StreamConnection even if the retries succeed? Where should I catch errors happening when all retry attempts fail?

Lately I've been receiving a few `2 UNKNOWN: 408:Request Timeout` errors, so I want to check if I'm safe to ignore them since there's an retry logic

- What you're trying to do
Understand how to safely handle errors.

- What code you've already tried

```JS
    const connection = await writeClient.createStreamConnection({
       streamId,
    });

    connection.onConnectionError(async (error) => {
       logger.error(error)
    });
```

- Any error messages you're getting 
 `2 UNKNOWN: 408:Request Timeout` 
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Thanks!

**Comment by alvarowolfx** [comment]
hey @brantian, thanks for the question. We've added more retry logic on the recent PR #443 and release v4.6.0, before that, our logic was mostly to reconnect the `StreamConnection` than doing any kind of write retries. To have write retries you have to enable then with the `enableWriteRetries` method on the `WriteClient`.

So we can list here two major scenarios of retry: 

* The `onConnectionError` will be called on any error happens during the `StreamConnection` lifecycle, it's mostly geared towards monitoring errors and in some scenarios leave for the user to handle any error case that is not yet handled automatically by the library. In this case here is a bit harder to keep track of which `PendingWrite` caused the issue, so depending on the error, is safer to just retry/abort everything that was made on that given Stream. 

* Errors that can be associated with a given `PendingWrite` are a bit easier to reason about, as there are cases that we can  retry automatically (if writeRetries are enabled) and the `PendingWrite.getResult()` promise will either results successfully or will throw an error if it fails. In the failing case, you can also retry if is a case that is not handled by our retry mechanism (like for example, currently we are still not handling RESOURCE_EXHAUSTED).

What kind of `Stream` are you using ? Default, Pending, Buffered or Committed ? Depending on your scenario for example, you can use a `Pending` stream, call `appendRows` multiple times to write data, make sure all `PendingWrite`s succeed, call `StreamConnection.finalize` to end the stream and check the number of rows written and if is all good, you can `batchCommit` the stream. There are different scenarios and different ways to write data using the Storage Write API depending on the guarantees that are needed. 

The `UNKNOWN: 408:Request Timeout` error is a odd one, as 408 is not a gRPC status code. Is that error being thrown via the `onConnectionError` callback or from an individual `PendingWrite` failing ?

**Comment by brantian** [comment]
Hi @alvarowolfx, thanks for your answer; that's very clarifying!

I'm using a `Pending` stream, and I'm doing something quite similar to what you suggested, I'm just not checking the number of rows before calling `batchCommit` yet, but I'll add this step as well. My main concern is making sure I'm not losing data due to unhandled errors, so this approach sounds reasonable!

As for the `UNKNOWN: 408:Request Timeout` error, it's being thrown via the `onConnectionError` callback. I'm observing it with this log call:

```JS
    connection.onConnectionError((error) => {
       logger.error(error.message)
    });
 ```

**Comment by alvarowolfx** [comment]
@brantian do you have any other question about error handling ? can I close this issue ?

**Comment by brantian** [comment]
@alvarowolfx it can be closed, thanks!
