### ISSUE TITLE
4.7.0 build folder has no build file

### ISSUE THREAD

**Issue by lzhao1AtWoolworths** [googleapis/nodejs-bigquery-storage#457]
Hi there,
- What you're trying to do
I was doing an "npm install" of this package and the build folder
`@google-cloud/bigquery-storage/build`
appeared to have only the `package.json` file. All import statements (Typescript) that referred to this module reported that 
> Cannot find module '@google-cloud/bigquery-storage' or its corresponding type declarations.ts(2307)

- What code you've already tried
I checked the npm repository's files and it did look strange:

![Screenshot 2024-05-09 at 09 35 45](https://github.com/googleapis/nodejs-bigquery-storage/assets/149639496/8e2255c5-ca4b-488f-a7d9-cf840776cdd7)

I switched to use the fixed version 4.6.0 and more files became available in the `build` foler. 

- Any error messages you're getting
All builds of my service that were built successfully some days ago are now failing because of that. 

Can someone have a look please? The issue seems just that build files weren't packaged/uploaded onto 4.7.0 on npm. 

Regards,
Lee

**Comment by alvarowolfx** [comment]
hey @lzhao1AtWoolworths @larssn I'm gonna take a look on that, but I'll probably have to remove version 4.7.0 and release a new version.

**Comment by alvarowolfx** [comment]
I changed v4.6.0 to be the latest on NPM while I investigate what happened with 4.7.0. I'll probably release v4.8.0 on PR #456 so we can have a good version again with all working.
