### ISSUE TITLE
ReadClient throws on null values

### ISSUE THREAD

**Issue by kitsunde** [googleapis/nodejs-bigquery-storage#518]
https://github.com/googleapis/nodejs-bigquery-storage/blob/main/src/reader/arrow_transform.ts#L146 this can be `null` and `null` is an object, which causes nullable fields to throw. For example in this case:

```
fieldData.toString();
>>> {"column_name": null}
```

Then it gets passed to https://github.com/googleapis/nodejs-bigquery-storage/blob/main/src/reader/arrow_transform.ts#L159 and enter the object path because `typeof null === 'object'` is `true` then break on `Object.keys(null)` in https://github.com/googleapis/nodejs-bigquery-storage/blob/main/src/reader/arrow_transform.ts#L168

> TypeError: Cannot convert undefined or null to object

**Comment by alvarowolfx** [comment]
thanks for the report @kitsunde, I'll work on fixing that and improving the test coverage for that
