### ISSUE TITLE
decodedData only contains the first object

### ISSUE THREAD

**Issue by jankrynauw** [googleapis/nodejs-bigquery-storage#99]
Looking at the `avroRows` property of the `data` object, there are 1024 rows on the first event.  The `decode()` method only returns the first element in the in the `data.avroRows.serializedBinaryRows` Buffer object.

https://github.com/googleapis/nodejs-bigquery-storage/blob/a3f7556dc9842d0f784d30afea60c814ab208a5a/samples/quickstart.js#L120

Here is a debug screenshot:
![Screenshot 2020-08-04 at 15 17 20](https://user-images.githubusercontent.com/18016598/89298478-ae262d80-d665-11ea-90ba-b9ad5024ac4b.png)

Should one not iterate through the rows? Something along the lines of:

![Screenshot 2020-08-04 at 15 19 09](https://user-images.githubusercontent.com/18016598/89298677-ec235180-d665-11ea-9e26-6a9d515eebbc.png)

**Comment by meredithslota** [comment]
@steffnay Probably this is a question / clarification but it might be a library bug - PTAL when you get a chance. :)
